//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TransCAD.rc
//
#define IDR_RT_MANIFEST                 1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_TRANSCAD                    103
#define IDR_APPLICATIONAUTO             104
#define IDR_DOCUMENTSAUTO               105
#define IDR_DOCUMENTAUTO                106
#define IDR_PARTDOCUMENTAUTO            107
#define IDR_PART                        108
#define IDR_FEATURES                    109
#define IDR_STDSKETCHFEATURE            110
#define IDR_STDSOLIDPROTRUSIONEXTRUDEFEATURE 111
#define IDR_STDSOLIDCUTEXTRUDEFEATURE   112
#define IDR_STDSOLIDFILLETCONSTANTFEATURE 113
#define IDR_STDSKETCHORIGIN             114
#define IDR_STDSKETCHVDIRECTION         115
#define IDR_STDSKETCHHDIRECTION         116
#define IDR_STDSKETCHGEOMETRIES         117
#define IDR_STDSKETCHCONSTRAINTS        118
#define IDR_STDSKETCHGEOMETRY           119
#define IDR_STDSKETCHCONSTRAINT         120
#define IDR_STDSKETCHCIRCLE             121
#define IDR_STDSKETCHCIRCULARARC        122
#define IDR_STDSKETCHCONTROLPOINT       123
#define IDR_STDSKETCHLINE               124
#define IDR_REFERENCES                  126
#define IDR_REFERENCE                   127
#define IDR_MAINFRAME                   128
#define IDR_PartTYPE                    129
#define IDR_EXPLICITMODELOBJECT         130
#define IDR_SKETCH                      131
#define IDR_SKETCHEDITOR                132
#define IDR_STDDEFAULTDATUMPLANEFEATUREAUTO 133
#define IDR_FEATURE                     134
#define IDR_REGISTRY1                   134
#define IDR_STDSOLIDPROTRUSIONSWEEPFEATURE 135
#define IDR_STDSOLIDPROTRUSIONREVOLVEFEATURE 136
#define IDR_STDSKETCHCENTERLINE         137
#define IDR_STDSOLIDOPERATEPATTERNRECTANGULARFEATURE 138
#define IDR_STDSOLIDCHAMFERFEATURE      139
#define IDR_STDSOLIDCUTREVOLVEFEATURE   140
#define IDR_STDSOLIDOPERATEPATTERNCIRCULARFEATURE 141
#define IDR_ISTDSOLIDHOLECOUNTERBOREDFEATUREAUTO 142
#define IDR_STDSOLIDHOLECOUNTERBOREDFEATUREAUTO 143
#define IDR_STDSOLIDHOLECOUNTERSUNKFEATURE 144
#define IDR_STDSKETCHHORIZONTAL         146
#define IDR_STDSKETCHPARALLEL           147
#define IDR_STDSKETCHPERPENDICULAR      148
#define IDR_STDSKETCHCOINCIDENTSAMEPOINTS 149
#define IDR_STDSKETCHVERTICAL           150
#define IDR_STDDATUMPLANEOFFSETFEATURE  151
#define IDR_ASSEMDOCUMENTAUTO           152
#define IDR_ASSEMAUTO                   153
#define IDR_STDSOLIDLOFTFACESFEATUREAUTO 158
#define IDR_COMPONENTAUTO               159
#define IDR_STDSOLIDLOFTSECTIONSFEATURE 160
#define IDR_STDSOLIDCUTSWEEPFEATURE     161
#define IDR_STDSOLIDHOLESIMPLEFEATURE   162
#define IDR_STDSOLIDSHELLFEATURE        163
#define IDR_STDSOLIDREVOLVEWITHEXTERNALAXISFEATURE 164
#define IDR_STDSOLIDDRAFTFEATURE        165
#define IDR_STDSOLIDOFFSETFEATURE       166
#define IDR_STDSOLIDIMPORTEDBREPFEATURE 167
#define IDR_SOLID                       168
#define IDR_FACES                       169
#define ID_SCRIPT_INTERFACE             170
#define IDR_EDGES                       171
#define IDR_FACE                        172
#define IDR_EDGE                        173
#define IDR_VERTICES                    174
#define IDR_VERTEX                      175
#define IDR_POINT3D                     176
#define IDR_AXIS1                       177
#define IDR_STDASSEMCONSTRAINTS         189
#define IDR_STDASSEMCONSTRAINT          190
#define IDR_TESTCLASS                   191
#define IDR_STDASSEMCONSTRAINTCOAXIAL   192
#define IDR_STDASSEMCONSTRAINTINCIDENCE 194
#define IDR_STDASSEMCONSTRAINTDISTANCE  195
#define IDR_STDASSEMCONSTRAINTANGLE     196
#define VersionMajor                    1000
#define IDC_VERSION                     1000
#define VersionBuild                    1003
#define ReleaseDate                     1004
#define ID_OPEN_XML_FILE                32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           197
#endif
#endif
